name: Testing (Cypress)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: https://registrynpm.storefrontcloud.io

      - name: Install dependencies
        run: yarn install

      - name: Serve application
        run: yarn dev &

      - name: Run cypress tests
        run: yarn test:e2e:run
